name: tic_tac_toe
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  get: ^4.6.6
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  socket_io_client: ^3.0.0
  dio: ^5.4.3+1
  shared_preferences: ^2.3.2
  get_it: ^8.0.2
  dartz: ^0.10.1
  chiclet: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/pngs/app-icon.png"
  image_path_ios: "assets/pngs/app-icon.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/pngs/app-icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/pngs/app-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/pngs/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/jsons/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/font/Outfit-Black.ttf
        - asset: assets/font/Outfit-Bold.ttf
        - asset: assets/font/Outfit-ExtraBold.ttf
        - asset: assets/font/Outfit-ExtraLight.ttf
        - asset: assets/font/Outfit-Light.ttf
        - asset: assets/font/Outfit-Medium.ttf
        - asset: assets/font/Outfit-Regular.ttf
        - asset: assets/font/Outfit-SemiBold.ttf
        - asset: assets/font/Outfit-Thin.ttf
